name: CodeCov

on:
  pull_request:
    branches: [master, develop]
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      os: ubuntu-latest
      python-version: "3.8"

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "2"
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Generate Report
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install coverage
          coverage run -m unittest discover
      - name: Upload Coverage to Codecov
        uses: actions/codecov-action@v2
        with:
          fail_ci_if_error: true
